---
- name: Define packackages to process.
  ansible.builtin.set_fact:
    _packages_present: '{{ pedrohdz_devenv_packages | pedrohdz.devenv.present_packages }}'
    _packages_absent: '{{ pedrohdz_devenv_packages | pedrohdz.devenv.absent_packages }}'
    _packages_macport_variants: '{{ pedrohdz_devenv_packages | pedrohdz.devenv.present_macport_variants }}'
    _packages_alternatives: '{{ pedrohdz_devenv_packages | pedrohdz.devenv.alternatives }}'

- name: List of packages to process.
  ansible.builtin.debug:
    msg: |
      Packages to ensure are absent:
        {{ _packages_absent | join(" ") | default("NONE", true) }}

      Packages to ensure are present:
        {{ _packages_present | join(" ") | default("NONE", true) }}

      Package alternative selections to ensure are present:
        {{ _packages_alternatives | map('first') | join(" ") | default("NONE", true) }}

      {% if ansible_pkg_mgr == 'macports' -%}
      Macport variants to ensure are present:
        {{ _packages_macport_variants | map('join', '') | join(" ") | default("NONE", true) }}
      {%- endif -%}

- include_tasks: process-macports.yaml
  when: |
    ((ansible_pkg_mgr == 'macports') and (pedrohdz_devenv_packages_macosx_pkg_mgr == 'default'))
      or ((ansible_distribution == 'MacOSX') and (pedrohdz_devenv_packages_macosx_pkg_mgr in ['all', 'macports']))

- include_tasks: process-brew.yaml
  when: |
    ((ansible_pkg_mgr == 'brew') and (pedrohdz_devenv_packages_macosx_pkg_mgr == 'default'))
      or ((ansible_distribution == 'MacOSX') and (pedrohdz_devenv_packages_macosx_pkg_mgr in ['all', 'brew']))

- include_tasks: process-apt.yaml
  when: ansible_pkg_mgr == 'apt'
...
