---
- name: Define packackages to process.
  ansible.builtin.set_fact:
    _packages_present: '{{ pedrohdz_packages | pedrohdz.common.present_packages }}'
    _packages_absent: '{{ pedrohdz_packages | pedrohdz.common.absent_packages }}'
    _packages_macport_variants: '{{ pedrohdz_packages | pedrohdz.common.present_macport_variants }}'
    _packages_alternatives: '{{ pedrohdz_packages | pedrohdz.common.alternatives }}'

- name: List of packages to process.
  ansible.builtin.debug:
    msg: |
      Packages to ensure are absent:
        {{ _packages_absent | join(" ") | default("NONE", true) }}

      Packages to ensure are present:
        {{ _packages_present | join(" ") | default("NONE", true) }}

      Package alternative selections to ensure are present:
        {{ _packages_alternatives }}

      {% if ansible_pkg_mgr == 'macports' -%}
      Macport variants to ensure are present:
        {{ _packages_macport_variants | map('join', '') | join(" ") | default("NONE", true) }}
      {%- endif -%}

- import_tasks: process-macports.yaml
  when: ansible_pkg_mgr == 'macports'

- import_tasks: process-apt.yaml
  when: ansible_pkg_mgr == 'apt'
...
