---
# - name: Update packages cache
#   community.general.macports:
#     selfupdate: true
#     upgrade: false
#   become: '{{ pedrohdz_become_for_all }}'
#   when: pedrohdz_packages_update_cache
#
# - name: Upgrade installed packages
#   community.general.macports:
#     selfupdate: false
#     upgrade: true
#   become: '{{ pedrohdz_become_for_all }}'
#   when: pedrohdz_packages_upgrade_installed


- name: Ensure absent Macports ports.
  community.general.macports:
    name: '{{ _packages_absent }}'
    selfupdate: false
    state: absent
    upgrade: false
  become: '{{ pedrohdz_become_for_all }}'

- name: Ensure present Macports ports.
  community.general.macports:
    name: '{{ _packages_present }}'
    selfupdate: false
    state: present
    upgrade: false
  become: '{{ pedrohdz_become_for_all }}'

- name: Ensure present Macport variant ports.
  community.general.macports:
    name: '{{ item[0] }}'
    variant: '{{ item[1] }}'
    selfupdate: false
    state: present
    upgrade: false
  become: '{{ pedrohdz_become_for_all }}'
  loop: '{{ _packages_macport_variants }}'

...
